# Generated by Django 6.1 on 2026-08-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=1000, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=1000, null=True, verbose_name='Заголовок')),
                ('image', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('True', 'Да'), ('False', 'Нет')], default='True', max_length=15, verbose_name='Статусы')),
                ('create_at', models.DateField(auto_now=True, verbose_name='Создать в')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=1000, verbose_name='Ф.И.О')),
                ('phone', models.CharField(max_length=1000, verbose_name='телефон')),
                ('car_number', models.CharField(max_length=1000, verbose_name='Номер автомобиля')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водитель',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1000, verbose_name='Пользователь ID')),
                ('username', models.CharField(max_length=1000, verbose_name='Имя пользователя')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('create_at', models.DateField(auto_now=True, verbose_name='Создать в')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=1000, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=1000, null=True, verbose_name='Заголовок')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('status', models.CharField(choices=[('True', 'Да'), ('False', 'Нет')], default='True', max_length=15, verbose_name='Статусы')),
                ('create_at', models.DateField(auto_now=True, verbose_name='Создать в')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукт',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000, verbose_name='геолокация')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='полный адрес')),
                ('full_address_uz', models.TextField(blank=True, null=True, verbose_name='полный адрес')),
                ('full_address_ru', models.TextField(blank=True, null=True, verbose_name='полный адрес')),
                ('user_id', models.CharField(max_length=1000, verbose_name='пользователь ID')),
                ('phone', models.CharField(max_length=1000, verbose_name='телефон')),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='код')),
                ('language', models.CharField(blank=True, max_length=8, null=True, verbose_name='язык')),
                ('product_data', models.JSONField(blank=True, default=dict, verbose_name='Данные о продукте')),
                ('status', models.CharField(choices=[('New', 'Новый'), ('Accepted', 'Принял'), ('Rejected', 'Отклоненный'), ('Expired', 'Истекший')], default='New', max_length=50, verbose_name='Статусы')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Линк')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Создать в')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.driver', verbose_name='Водитель')),
                ('product', models.ManyToManyField(to='home.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1000, verbose_name='пользователь ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True, verbose_name='пользователь')),
                ('quantity', models.IntegerField(default=1, verbose_name='количество')),
                ('total_price', models.CharField(max_length=1000, verbose_name='общая цена')),
                ('status', models.CharField(choices=[('New', 'Новый'), ('Not-accepted', 'Не-принято')], default='New', max_length=50, verbose_name='Статусы')),
                ('create_at', models.DateField(auto_now=True, verbose_name='Создать в')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
